### ISSUE TITLE
I want to configure root with empty password, what can I do?

### ISSUE THREAD

**Issue by JimmyShi22** [mirromutth/mysql-action#17]
my config:
``` yml
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: 'root'
          mysql password: 'test'
```

but failed when I login with root and empty password
