### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by saguileran** [mirromutth/mysql-action#32]
I am using this action to deploy a Jupyter book with java kernel and I want that jupyter books interact with the database.  Nevertheless, I am getting the following error:

````{bash}
java.sql.SQLException: Access denied for user 'dba'@'localhost' (using password: YES)
````

The server is working, but for some reason the user is not allowed to use is. I am using the action as follows:

```yml
- name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
  
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        mysql version: 'latest' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'Universidad' # Optional, default value is "test". The specified database which will be create
        mysql root password: "$12345679" # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'dba' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: "$123456789" # Required if "mysql user" exists. The password for the "mysql user"
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql start
```

The repo is https://github.com/uETITC/ProgrammingII-2024-2.

How can I solve the problem?
